### PR TITLE
create exercise-versioning.md

### LINKED ISSUE #25: Document exercise versioning
These are currently documented in
https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#exercise-versioning

They should be moved into the https://github.com/exercism/docs/tree/master/maintaining-a-track directory in this repository.

That will take two pull requests. One in this repository to add the new file, and one in the https://github.com/exercism/x-common repository to delete the copy that was moved from the CONTRIBUTING.md file.

### PR DESCRIPTION
**Pull request by eclecticjohny**
Move copy from https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#exercise-versioning to  a separate file in https://github.com/exercism/docs/tree/master/maintaining-a-track

Fixes #25

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
What I'm missing in this document is a link to how an exercise's track version can be linked to the x-common exercise version. Perhaps that would be useful to mention, to prevent people from coming up with their own versioning scheme.

**Comment by eclecticjohny** [comment]
It looks as though the x-common exercise can be versioned in the canonical-data.json file in the exercises directory, however, I am failing to to see how that version is linked to in a language specific exercise.

**Comment by kytrinyx** [comment]
Thank you @eclecticjohny! 🌷 

> What I'm missing in this document is a link to how an exercise's track version can be linked to the x-common exercise version.

I don't know if we ever decided how to do that. Track versioning predates exercise versioning.

My suggestion would be to specify that the versions are unrelated, and to increment track versions only if the test suite introduces a breaking change.

**Comment by ErikSchierboom** [comment]
That's fine, I was thinking about test generators. For test generators, you can and probably should link to the x-common version used to generate the tests.

**Comment by eclecticjohny** [comment]
This section of the documentation is unclear for me and it looks as though some things need  to be ironed out with the versioning. I am sorry but I am unable to complete this request as it is stated at this time. I will try and help the project in another way in the future. Thanks.

**Comment by kytrinyx** [comment]
No, @eclecticjohny, we can merge this as is and update the documentation later. It's useful to have this conversation to figure out if we had to do some updating to the file up front. That's part of the process.

**Pull request merged**
