### PR TITLE
Add note to maintainer docs regarding alumnus key

### PR DESCRIPTION
**Pull request by robphoenix**
Ref: https://github.com/exercism/v2-feedback/issues/81

### CODE REVIEW

**Comment by iHiD** [comment]
@robphoenix Thanks. FYI, we're also going to accept `true` as an option, which sets to `alumnus`. I'm not sure if we want to be explicit about this or not?

**Review by iHiD — APPROVED** [review]

**Comment by robphoenix** [comment]
@iHiD Will `false` be a valid option? If not then it might be preferable to leave as-is so it's not implied that `false` is valid? Otherwise I'll update this to mention it.

**Comment by iHiD** [comment]
@robphoenix The logic is that `true` is already everywhere so we want to keep it working, but you're right - we should probably deprecate it so let's leave it out of the text. Happy for you to merge. Thank you 💙

**Comment by robphoenix** [comment]
No worries. Thanks @iHiD :heart: 
I'll leave https://github.com/exercism/v2-feedback/issues/81 open for you to close when you're done with it internally.

**Comment by kytrinyx** [comment]
> FYI, we're also going to accept true as an option

I'd rather not, to be honest, because then we need to jump through hoops in configlet to handle both strings and booleans in the same field (not super straight-forward).

**Comment by kytrinyx** [comment]
Update: I'd rather not be explicit about `true` -- totally fine to handle it for the repos where it's already that way. But Configlet should complain about it.

**Comment by kytrinyx** [comment]
... and @robphoenix is way ahead of me :) https://github.com/exercism/configlet/issues/75

Ok. Ignore me. It's all good :-)

**Pull request merged**
