### PR TITLE
Fix broken link to goal-of-exercism

### PR DESCRIPTION
**Pull request by tcNickolas**

### CODE REVIEW

**Review by rpottsoh — CHANGES_REQUESTED** [review]
Good find.  I see another broken link on line 59.  let me know if you need help on that one.

**Comment by tcNickolas** [comment]
Indeed, I've noticed it too but haven't realized that this was supposed to be a link :-)
I've updated the pull request

**Review by kytrinyx — APPROVED** [review]
Awesome! Thanks so much for catching these. ✨ 🌷 ✨

**Review by rpottsoh — APPROVED** [review]
Thanks for making these fixes.

**Comment by ZacharyRSmith** [comment]
looks like there are at least 23 other broken links, according to this tool: http://www.brokenlinkcheck.com/broken-links.php#status, which gave enough info to track down the link.  the links would make good first-patch issues.

the tool stopped after 3000 pages.  there is probably a more comprehensive tool for free.

**Comment by ZacharyRSmith** [comment]
screen shot 2017-10-13 at 11 20 01 pm

**Comment by rpottsoh** [comment]
@ZacharyRSmith this is a nice find.  You should probably share this as a new issue in [exercism/discussions](https://github.com/exercism/discussions).

**Pull request merged**
