### PR TITLE
finding-your-way.md: Correct errors in MD.

### PR DESCRIPTION
**Pull request by rpottsoh**
Several mistakes corrected in MD relating to:
- old references to repo `x-common` that have been updated for repo `problem-specifications`.  
- 4 places where a bullet point was called for but a `1.` level topic was indicated.  
- 2 places where a reference link was not spelled correctly.

Each of these changes is contained within its own commit.

### CODE REVIEW

**Review by petertseng — COMMENTED** [review]
> Also changed line 54 from numeric index to a bullet.

To me it sounds like that should be a separate commit. https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/pull-request-guidelines.md says the subject line should avoid *and*; I'm inferring this to mean that commits should make one logical change and that the body of the commit should not contain *and* and other similar words. (I've taken liberties with the interpretation here, so my interpretation may be incorrect)

Should this change also be applied to the number in the following sections?

* https://github.com/exercism/docs/blob/master/finding-your-way.md#i-would-like-to-help-i-know--want-to-get-better-at-web-programming
* https://github.com/exercism/docs/blob/master/finding-your-way.md#i-would-like-to-help-i-know--want-to-get-better-at-ruby
* https://github.com/exercism/docs/blob/master/finding-your-way.md#i-would-like-to-help-i-know--want-to-get-better-at-go

> Fix exersism-bugs reference.

To me it sounds like that should be a separate commit.

**Comment by rpottsoh** [comment]
@petertseng thanks for pointing out these issues with this PR.  It looks like I need at least three commits...

**Comment by rpottsoh** [comment]
My commit message for sha 398b9a is erroneous.  I wasn't understanding what was happening at the time I wrote it.  I understand now that the links containing `?documentation` are fine.  I contemplated updating the commit message but found myself getting bogged down in git logic and decided to give up on that.  I figure I can make sure that blurb is omitted in the commit message when this PR is squashed and merged.

**Review by kytrinyx — APPROVED** [review]
This all looks great! Thanks so much for catching those. I think the bullet vs number was an early misunderstanding about how markdown works that kept getting perpetuated.

**Pull request merged**
