### PR TITLE
glossary.md: update link to problem-specfications repo

### PR DESCRIPTION
**Pull request by rpottsoh**

### CODE REVIEW

**Review by petertseng — COMMENTED** [review]
I would recommend not leaving an unused reference to x-common-repo at the bottom of the file (line 25)

**Comment by petertseng** [comment]
s/dangling/unused/

**Comment by rpottsoh** [comment]
Thanks, got it.

**Review by petertseng — APPROVED** [review]
Difference: previous "repository" was included in the link text, now is not. I don't care either way.

It seems to make sense to squash.

I wonder if there was a very specific reason to use a named reference `x-common-repo` rather than put the destination inline (as this PR does). It had been this way since https://github.com/exercism/docs/pull/37 but there was only one use of the x-common-repo name, and I find named reference most useful when the destination is long or used multiple times (neither is true here). So I don't care.

Maybe it is put there in preparation for the reference being used multiple times? Don't know. Maybe someone else does.

**Comment by rpottsoh** [comment]
Thanks @petertseng some good questions.  No reasons are immediately evident.  I will go ahead and squash and merge.

**Pull request merged**
